version: "3.9"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: ignite
      POSTGRES_DB: rentx
    ports:
      - 4343:5432
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass ignite

  # app:
  #   build: .
  #   container_name: rentx
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database_ignite
  #   depends_on:
  #     - database_ignite

volumes:
  pgdata:
    driver: local
